import type { Metadata } from "next";
import { Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { CurrencyProvider } from "@/lib/currency-context";
import { ApiKeyProvider } from "@/lib/api-key-context";
import { GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";
import { CookieBanner } from "@/components/cookie-banner";
import "./globals.css";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Receipt Scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jakartaSans.variable} ${jetbrainsMono.variable}`}
    >
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID!} />
      <body className="antialiased" suppressHydrationWarning>
        {/*
          Consent default runs before GTM so GA knows the storage state immediately.
          On returning visits we read localStorage here — not in React — so the
          correct value is in the dataLayer before any GTM tag fires.
        */}
        <Script id="ga-consent-default" strategy="beforeInteractive">{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          var stored = '';
          try { stored = localStorage.getItem('cookie_consent') || ''; } catch(e) {}
          gtag('consent', 'default', {
            analytics_storage: stored === 'granted' ? 'granted' : 'denied'
          });
        `}</Script>
        <CurrencyProvider>
          <ApiKeyProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </ApiKeyProvider>
        </CurrencyProvider>
        <CookieBanner />
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
